### ISSUE TITLE
backend TODO

### ISSUE THREAD

**Issue by mu-hun** [book-case/bookcase#2]
more details : [Search Results : 'TODO'](https://github.com/book-case/bookcase/search?p=1&q=TODO)

## `routes/`
* `user.js`
  * [ ] permission check
  * [ ] csrf check
  * [ ] delete user
* `image.js`
  * [ ] id / volume / page
* `read.js`
  * [ ] Show volume info (Title, Volume, Author, Tags)
  * [ ] send pages
* `book.js`
  * [ ] create a new book and return id
  * [ ] check for id existence. (if not, reject it)
  * [ ] check for volume existence. (if exists, reject it)
* `login.js`
  * [ ] check forms and login, update session
* `tag.js`
  * [ ] send tags and book counts of tag.
* `signup.js`
  * [ ] sanitize forms, if registration is allowed, register a user

## `src/`
* `verify-user.js`
  * [ ] add authentications

**Comment by mu-hun** [comment]
이 플젝 반려된 거 맞죠?

**Comment by HelloWorld017** [comment]
@x86chi 누구신가 했는데
